In [6]:
import collections
import pandas as pd
words=[]
total_w_c=[]
word=[]
counts=[]
file=open("comment.txt","r+")
wordcount={}
for word in file.read().split():
    
        word = word.lower()

        if word not in wordcount:
            wordcount[word] = 1
        else:
            wordcount[word] += 1
for count,v in wordcount.items():
    words.append(count)
    total_w_c.append(v)
    
test_df = pd.DataFrame({'Words':words,'Counts': total_w_c})

df=test_df.sort_values(by=['Counts'],ascending=False)
df.reset_index(drop='index', inplace=True)
df=df[['Words','Counts']]
df

                 Words  Counts
0                  the    5240
1                  and    2771
2                    a    2241
3                   to    2149
4                    i    2022
5                   of    1569
6                  was    1523
7                wings    1414
8                   is    1040
9                   in    1027
10                were     947
11                 for     929
12                 but     898
13                  we     870
14                  it     835
15                they     797
16                that     767
17             buffalo     700
18                 not     688
19                  on     683
20                 you     659
21                 are     590
22                with     580
23                this     568
24                  my     561
25                have     550
26                 had     533
27                  at     501
28                 bar     471
29              anchor     449
...                ...     ...
9727           flavor/       1
9728        ourselves.       1
9729            price"       1
9730              "buy       1
9731             media       1
9732            praise       1
9733            bar.if       1
9734        successful       1
9735            basis,       1
9736       friendlier,       1
9737      knick-knacks       1
9738          side.the       1
9739              top,       1
9740            slice.       1
9741             way),       1
9742        depth.late       1
9743           profile       1
9744           complex       1
9745          suicide,       1
9746           milder)       1
9747          wing!the       1
9748         dripping.       1
9749            sloppy       1
9750            argue.       1
9751            wing",       1
9752         duffswing       1
9753  conclusion:sauce       1
9754        enjoyfinal       1
9755     opinion!sauce       1
9756        overhyped!       1

[9757 rows x 2 columns]

In [159]:
df.to_csv('word_count.csv')